apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vj0nhmp2r-python 
  janus-idp.io/tekton: vj0nhmp2r-python
  backstage.io/kubernetes-id: vj0nhmp2r-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vj0nhmp2r-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml